workflows:
  react_native_build:
    name: React Native Build
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 18.16.0
        REACT_NATIVE_VERSION: latest
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android && ./gradlew assembleRelease
      - name: Build iOS app
        script: |
          cd ios && pod install --quiet
          xcodebuild -workspace ios/YourApp.xcworkspace -scheme YourApp -sdk iphoneos -configuration Release
    artifacts:
      - android/app/build/outputs/**/*.apk
      - ios/build/**/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
